import { formatDate } from "../../../components/admin/utils/date";

export const newApplicantsData = [
    {
        name: "Alice Johnson",
        address: "8, Surulere Street, Idumota, Lagos.",
        dateApplied: formatDate("11/24/2020"),
        type: "New Application",
        status: "Completed",
    },
    {
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Rejected",
    },
    {
        name: "Jane Smith",
        address: "10, Yedseram Street, Maitama, FCT.",
        dateApplied: formatDate("3/15/2023"),
        type: "Reissue",
        status: "Processing",
    },
    {
        name: "Sani Yusuf Ibrahim",
        address: "5, Ogun Close, Panseke, Abeokuta.",
        dateApplied: formatDate("3/15/2023"),
        type: "Renewal",
        status: "In Transit",
    },
    {
        name: "Halimah Sadiya Adam",
        address: "1, Ibidun Street, Ketu, Lagos.",
        dateApplied: formatDate("3/15/2023"),
        type: "New Application",
        status: "On Hold",
    },
    {
        name: "Alice Johnson",
        address: "8, Surulere Street, Idumota, Lagos.",
        dateApplied: formatDate("11/24/2020"),
        type: "New Application",
        status: "Completed",
    },
    {
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Rejected",
    },
    {
        name: "Jane Smith",
        address: "10, Yedseram Street, Maitama, FCT.",
        dateApplied: formatDate("3/15/2023"),
        type: "Reissue",
        status: "Processing",
    },
    {
        name: "Sani Yusuf Ibrahim",
        address: "5, Ogun Close, Panseke, Abeokuta.",
        dateApplied: formatDate("3/15/2023"),
        type: "Renewal",
        status: "In Transit",
    },
    {
        name: "Halimah Sadiya Adam",
        address: "1, Ibidun Street, Ketu, Lagos.",
        dateApplied: formatDate("3/15/2023"),
        type: "New Application",
        status: "On Hold",
    },
    {
        name: "Alice Johnson",
        address: "8, Surulere Street, Idumota, Lagos.",
        dateApplied: formatDate("11/24/2020"),
        type: "New Application",
        status: "Completed",
    },
    {
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Rejected",
    },
    {
        name: "Jane Smith",
        address: "10, Yedseram Street, Maitama, FCT.",
        dateApplied: formatDate("3/15/2023"),
        type: "Reissue",
        status: "Processing",
    },
    {
        name: "Sani Yusuf Ibrahim",
        address: "5, Ogun Close, Panseke, Abeokuta.",
        dateApplied: formatDate("3/15/2023"),
        type: "Renewal",
        status: "In Transit",
    },
    {
        name: "Halimah Sadiya Adam",
        address: "1, Ibidun Street, Ketu, Lagos.",
        dateApplied: formatDate("3/15/2023"),
        type: "New Application",
        status: "On Hold",
    },
    {
        name: "Alice Johnson",
        address: "8, Surulere Street, Idumota, Lagos.",
        dateApplied: formatDate("11/24/2020"),
        type: "New Application",
        status: "Completed",
    },
    {
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Rejected",
    },
    {
        name: "Jane Smith",
        address: "10, Yedseram Street, Maitama, FCT.",
        dateApplied: formatDate("3/15/2023"),
        type: "Reissue",
        status: "Processing",
    },
    {
        name: "Sani Yusuf Ibrahim",
        address: "5, Ogun Close, Panseke, Abeokuta.",
        dateApplied: formatDate("3/15/2023"),
        type: "Renewal",
        status: "In Transit",
    },
    {
        name: "Halimah Sadiya Adam",
        address: "1, Ibidun Street, Ketu, Lagos.",
        dateApplied: formatDate("3/15/2023"),
        type: "New Application",
        status: "On Hold",
    },
    {
        name: "Alice Johnson",
        address: "8, Surulere Street, Idumota, Lagos.",
        dateApplied: formatDate("11/24/2020"),
        type: "New Application",
        status: "Completed",
    },
    {
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Rejected",
    },
    {
        name: "Jane Smith",
        address: "10, Yedseram Street, Maitama, FCT.",
        dateApplied: formatDate("3/15/2023"),
        type: "Reissue",
        status: "Processing",
    },
    {
        name: "Sani Yusuf Ibrahim",
        address: "5, Ogun Close, Panseke, Abeokuta.",
        dateApplied: formatDate("3/15/2023"),
        type: "Renewal",
        status: "In Transit",
    },
    {
        name: "Halimah Sadiya Adam",
        address: "1, Ibidun Street, Ketu, Lagos.",
        dateApplied: formatDate("3/15/2023"),
        type: "New Application",
        status: "On Hold",
    },
    {
        name: "Alice Johnson",
        address: "8, Surulere Street, Idumota, Lagos.",
        dateApplied: formatDate("11/24/2020"),
        type: "New Application",
        status: "Completed",
    },
    {
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Rejected",
    },
    {
        name: "Jane Smith",
        address: "10, Yedseram Street, Maitama, FCT.",
        dateApplied: formatDate("3/15/2023"),
        type: "Reissue",
        status: "Processing",
    },
    {
        name: "Sani Yusuf Ibrahim",
        address: "5, Ogun Close, Panseke, Abeokuta.",
        dateApplied: formatDate("3/15/2023"),
        type: "Renewal",
        status: "In Transit",
    },
    {
        name: "Halimah Sadiya Adam",
        address: "1, Ibidun Street, Ketu, Lagos.",
        dateApplied: formatDate("3/15/2023"),
        type: "New Application",
        status: "On Hold",
    },
    {
        name: "Alice Johnson",
        address: "8, Surulere Street, Idumota, Lagos.",
        dateApplied: formatDate("11/24/2020"),
        type: "New Application",
        status: "Completed",
    },
    {
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Rejected",
    },
    {
        name: "Jane Smith",
        address: "10, Yedseram Street, Maitama, FCT.",
        dateApplied: formatDate("3/15/2023"),
        type: "Reissue",
        status: "Processing",
    },
    {
        name: "Sani Yusuf Ibrahim",
        address: "5, Ogun Close, Panseke, Abeokuta.",
        dateApplied: formatDate("3/15/2023"),
        type: "Renewal",
        status: "In Transit",
    },
    {
        name: "Halimah Sadiya Adam",
        address: "1, Ibidun Street, Ketu, Lagos.",
        dateApplied: formatDate("3/15/2023"),
        type: "New Application",
        status: "On Hold",
    },
    {
        name: "Alice Johnson",
        address: "8, Surulere Street, Idumota, Lagos.",
        dateApplied: formatDate("11/24/2020"),
        type: "New Application",
        status: "Completed",
    },
    {
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Rejected",
    },
    {
        name: "Jane Smith",
        address: "10, Yedseram Street, Maitama, FCT.",
        dateApplied: formatDate("3/15/2023"),
        type: "Reissue",
        status: "Processing",
    },
    {
        name: "Sani Yusuf Ibrahim",
        address: "5, Ogun Close, Panseke, Abeokuta.",
        dateApplied: formatDate("3/15/2023"),
        type: "Renewal",
        status: "In Transit",
    },
    {
        name: "Halimah Sadiya Adam",
        address: "1, Ibidun Street, Ketu, Lagos.",
        dateApplied: formatDate("3/15/2023"),
        type: "New Application",
        status: "On Hold",
    },
    {
        name: "Alice Johnson",
        address: "8, Surulere Street, Idumota, Lagos.",
        dateApplied: formatDate("11/24/2020"),
        type: "New Application",
        status: "Completed",
    },
    {
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Rejected",
    },
    {
        name: "Jane Smith",
        address: "10, Yedseram Street, Maitama, FCT.",
        dateApplied: formatDate("3/15/2023"),
        type: "Reissue",
        status: "Processing",
    },
    {
        name: "Sani Yusuf Ibrahim",
        address: "5, Ogun Close, Panseke, Abeokuta.",
        dateApplied: formatDate("3/15/2023"),
        type: "Renewal",
        status: "In Transit",
    },
    {
        name: "Halimah Sadiya Adam",
        address: "1, Ibidun Street, Ketu, Lagos.",
        dateApplied: formatDate("3/15/2023"),
        type: "New Application",
        status: "On Hold",
    },
    {
        name: "Alice Johnson",
        address: "8, Surulere Street, Idumota, Lagos.",
        dateApplied: formatDate("11/24/2020"),
        type: "New Application",
        status: "Completed",
    },
    {
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Rejected",
    },
    {
        name: "Jane Smith",
        address: "10, Yedseram Street, Maitama, FCT.",
        dateApplied: formatDate("3/15/2023"),
        type: "Reissue",
        status: "Processing",
    },
    {
        name: "Sani Yusuf Ibrahim",
        address: "5, Ogun Close, Panseke, Abeokuta.",
        dateApplied: formatDate("3/15/2023"),
        type: "Renewal",
        status: "In Transit",
    },
    {
        name: "Halimah Sadiya Adam",
        address: "1, Ibidun Street, Ketu, Lagos.",
        dateApplied: formatDate("3/15/2023"),
        type: "New Application",
        status: "On Hold",
    },
    {
        name: "Alice Johnson",
        address: "8, Surulere Street, Idumota, Lagos.",
        dateApplied: formatDate("11/24/2020"),
        type: "New Application",
        status: "Completed",
    },
    {
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Rejected",
    },
    {
        name: "Jane Smith",
        address: "10, Yedseram Street, Maitama, FCT.",
        dateApplied: formatDate("3/15/2023"),
        type: "Reissue",
        status: "Processing",
    },
    {
        name: "Sani Yusuf Ibrahim",
        address: "5, Ogun Close, Panseke, Abeokuta.",
        dateApplied: formatDate("3/15/2023"),
        type: "Renewal",
        status: "In Transit",
    },
    {
        name: "Halimah Sadiya Adam",
        address: "1, Ibidun Street, Ketu, Lagos.",
        dateApplied: formatDate("3/15/2023"),
        type: "New Application",
        status: "On Hold",
    },
    {
        name: "Alice Johnson",
        address: "8, Surulere Street, Idumota, Lagos.",
        dateApplied: formatDate("11/24/2020"),
        type: "New Application",
        status: "Completed",
    },
    {
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Rejected",
    },
    {
        name: "Jane Smith",
        address: "10, Yedseram Street, Maitama, FCT.",
        dateApplied: formatDate("3/15/2023"),
        type: "Reissue",
        status: "Processing",
    },
    {
        name: "Sani Yusuf Ibrahim",
        address: "5, Ogun Close, Panseke, Abeokuta.",
        dateApplied: formatDate("3/15/2023"),
        type: "Renewal",
        status: "In Transit",
    },
    {
        name: "Halimah Sadiya Adam",
        address: "1, Ibidun Street, Ketu, Lagos.",
        dateApplied: formatDate("3/15/2023"),
        type: "New Application",
        status: "On Hold",
    },
    {
        name: "Alice Johnson",
        address: "8, Surulere Street, Idumota, Lagos.",
        dateApplied: formatDate("11/24/2020"),
        type: "New Application",
        status: "Completed",
    },
    {
        name: "John Doe",
        address: "24, Africana Street, Ojodu Berger, Lagos.",
        dateApplied: formatDate("10/12/2024"),
        type: "Renewal",
        status: "Rejected",
    },
    {
        name: "Jane Smith",
        address: "10, Yedseram Street, Maitama, FCT.",
        dateApplied: formatDate("3/15/2023"),
        type: "Reissue",
        status: "Processing",
    },
    {
        name: "Sani Yusuf Ibrahim",
        address: "5, Ogun Close, Panseke, Abeokuta.",
        dateApplied: formatDate("3/15/2023"),
        type: "Renewal",
        status: "In Transit",
    },
    {
        name: "Halimah Sadiya Adam",
        address: "1, Ibidun Street, Ketu, Lagos.",
        dateApplied: formatDate("3/15/2023"),
        type: "New Application",
        status: "On Hold",
    },
].map((data, index) => {
    const serialNumber = String(index + 1).padStart(5, "0");
    return {
        "s/n": serialNumber,
        ...data
    }
});

export const newApplicantsColumns = [
    { id: "s/n", header: "S/N" },
    { id: "name", header: "Name" },
    { id: "address", header: "Address" },
    { id: "dateApplied", header: "Date" },
    { id: "type", header: "Type" },
    { id: "status", header: "Status" },
];