export const centers = [
    {
        name: "FRSC Office, Oke-Gada, Ede",
        phone: "08012389045",
        email: "frscede@gmail.com",
        address: "FRSC Office, Oke-Gada, Ede, Osun State.",
        state: "Osun State",
        active: true,
    },
    {
        name: "Dannon Capture Center, Onitsha",
        phone: "08056789045",
        email: "dannon_onitsha@gmail.com",
        address: "Basilica, Sapele Road, Onitsha, Anambra State",
        state: "Anambra State",
        active: true,
    },
    {
        name: "VIO Office, Awka",
        phone: "08012389045",
        email: "vio_awka@gmail.com",
        address: "Number 8 mission Road Awka, Anambra State.",
        state: "Anambra State",
        active: true,
    },
    {
        name: "FRSC Center, Ebutte-meta",
        phone: "08056789045",
        email: "frsc_ebutte@gmail.com",
        address: "14 Agodgba Avenue Parkview State, Lagos State.",
        state: "Lagos State",
        active: true,
    },
    {
        name: "Dannon Capture Center",
        phone: "08012389045",
        email: "dannon_kano@gmail.com",
        address: "No 141 Zaria Road, Kano State.",
        state: "Kano State",
        active: true,
    },
    {
        name: "Road Safety Office",
        phone: "08056789045",
        email: "roadsafety@gmail.com",
        address: "Benin Lagos Expressway, Ore, Ondo State.",
        state: "Ondo State",
        active: true,
    },
    {
        name: "Dannon Group Center",
        phone: "08012389045",
        email: "dannon_akure@gmail.com",
        address: "Benin Lagos Expressway, Akure, Ondo State.",
        state: "Ondo State",
        active: true,
    },
    {
        name: "FRSC Office",
        phone: "08056789045",
        email: "frsc_ondo@gmail.com",
        address: "216 Oyemekun Road Akure, Ondo State.",
        state: "Ondo State",
        active: false,
    },
    {
        name: "VIO Office",
        phone: "08012389045",
        email: "vio_osun@gmail.com",
        address: "132, Gbongan-Osogbo Road, Osogbo, Osun State.",
        state: "Osun State",
        active: false,
    },
];